# -*- coding: utf-8 -*-
"""ServerStatus.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jV6IPunNeHdQqoCRX-kid66Wkn1TEcw5
"""

from bs4 import BeautifulSoup
import requests
import time
#import winsound #som para windows

user_world = input("Digite o nome do mundo: ") #pega o nome do mundo que o usuário queira
while(True):
  url = "https://na.finalfantasyxiv.com/lodestone/worldstatus/"   #Transforma o link em uma string
  html_content = requests.get(url).text                           #Usa o Requests para pegar o código do server HTTP (BS não faz isso)
  soup = BeautifulSoup(html_content, "html.parser")               #Transforma o documento html em um objeto BeautifulSoup

  mundo_nomes = []   #vetor dos nomes
  mundo_status = []  #vetor do status

  for mundo in soup.find_all("div", attrs={"class": "world-list__item"}):               #laço for para achar a classe dos mundos
    for ea in mundo.find_all("div", attrs={"class": "world-list__world_name"}):         #laço for para pegar o nome dos mundos
      mundo_nomes.append(ea.p.get_text())
    for ea2 in mundo.find_all("div", attrs={"class": "world-list__create_character"}):  #laço for para pegar o status dos mundos
      mundo_status.append(ea2.i['data-tooltip'])

  data = dict(zip(mundo_nomes, mundo_status)) #criação do dicionário
  print(data.get(user_world.lower().capitalize()))
  if data.get(user_world.lower().capitalize()) == "Creation of New Characters Available":
    #for i in range(5):
      #winsound.Beep(600, 800)
    time.sleep(10)
    break
  time.sleep(15)


#try except pra conexão de rede